### ISSUE TITLE
Can't download new programs using tinybldlin

### ISSUE THREAD

**Issue by DanielPrjct** [lcgamboa/tinybldlin#1]
Dear lcgamboa:

I'm trying to use your tinybldlin fork on Arch Linux, for programming a PIC16F887 at 20 MHz which is the core of OSIMPLC, my Open Hardware + Free Software project for educative purposes.

Using USBPICPROG (a OH + FS PIC programmer) I've downloaded a modified tinybld .hex firmware on PIC (attached in .zip archive with its .asm).
This firmware works very well with the original TINYBLDWIN v1.10.6 for Windows (by Claudiu Chiculita) running under Wine on my Arch system.
The only special configuration I've stated in TINYBLDWIN v1.10.6 to allow download new user programs (.hex) is to check "Ignore unknow data send by PIC until K is received" in the Option tab.

But TINYBLDWIN v1.10.6 is not Free (Libre) software, and its sources are not available.

So, looking for a Free (Libre) alternative, I've installed your fork.
I can run tinybldlin on Arch; using its included Terminal I can communicate with PIC running a downloaded program (through TINYBLDWIN), and I can receive PIC transmited data.

But I can't use tinybldlin to download a new program!

CheckPIC function works well:
Connected to /dev/ttyUSB0 at 19200
Searching for PIC ...
Found:16F 886/887

But Write Flash function hangs at start with following message:
Connected to /dev/ttyUSB0 at 19200
HEX:83 days old,INX32M,16Fcode+cfg,total=2646 bytes.
Searching for PIC ...
Found:16F 886/887

tinybldlin progress bar shows a little blue sector, but remains stucked forever; download process hangs.

To unhang this process, I have only two ways:
1. pressing again Write Flash button or CheckPIC button, relaunches PIC search, but both ends in an Error message "Searching for PIC ...Not found,  ERROR!";
2. killing tinybldlin.

I'm using a stripped pictype.py with only two definitions (my OSIMPLC can only take on board a PIC16F887, or a PIC18F4520):
----------------------
def pic_type(pt):
    
    if pt==0x36:
        PicType="16F 886/887";
        max_flash=0x2000;
        bsize=100;   
    elif pt==0x41:
        PicType="18F 252o/452o";
        max_flash=0x8000;
        bsize=200;
    else:
        PicType="Microcontroller not supported or not detected";
        max_flash=None;
        bsize=None;

    family=None

    if (pt==0x36):
        family="16F88X"
   
    elif (pt==0x41):
        family="18F452X"
           
    return PicType, max_flash, family, bsize
----------------------------------------------------------

Could you kindly see on this issue and tell me how to proceed?
Your help will be welcome!

Best regards,
Daniel
danielmirkin at gmail dot com

[PIC16F887_20MHz_firmware.zip](https://github.com/lcgamboa/tinybldlin/files/2668914/PIC16F887_20MHz_firmware.zip)

**Comment by lcgamboa** [comment]
I tested your modified  bootloader on debian unstable and ran smoothly with the changes that you have suggested. I will try to use Arch linux to try reproduce the problem.

**Comment by DanielPrjct** [comment]
Dear lcgamboa:

Thanks for your quick reply!

SOLVED!!! (MY FAULT):

I made a mistake in my modified pictype.py:

if (pt==0x36):
    family="16F88X"

Must be:

if (pt==0x36):
    family="16F8XX"

NOW, TINYBLDLIN WORKS VERY WELL!

I'm so sorry for the noise I've created in your project.
BTW: being 2020 the EOL of python2, do you will migrate tinybldlin to python3?

Best regards,
Daniel
