### ISSUE TITLE
tinybldlin on python3: some issues

### ISSUE THREAD

**Issue by DanielPrjct** [lcgamboa/tinybldlin#2]
Dear lcgamboa:

I'm using your new python3 version of tinybldlin, commit d7cf21b (thanks you, very much).

I've found various issues (not critical):

---  

Serial Port Search does not work at all, it is unable to find ttyUSB0 (virtual port via USB adapter).  

However, manually asigning /dev/ttyUSB0 on Comm box allows to communicate tinybldlin with PIC, via USB adapter based on CH340 driver, without problems.  
After connecting, both Check PIC and Write Flash works OK.  

---  

Using python3 version, some warnings arise on terminal:

Launching tinybldlin:  
<code>  
$ python ./tinybldlin.py  
./tinybldlin.py:135: DeprecationWarning: Gtk.StatusIcon.set_from_file is deprecated  
  self.status_icon.set_from_file(blue)
</code>  

Search PIC without PIC reset:  
<code>  
Not found press PIC reset...  
 Error, PIC not recognized (protocol error)  
./tinybldlin.py:339: PyGIDeprecationWarning: GObject.timeout_add is deprecated; use GLib.timeout_add instead  
  gobject.timeout_add(2000, self.on_timeout)  
</code>  

---

tinybldlin window can not allows horizontal resize (vertical resize is allowed).  

My system: Arch Linux with LXQt DE  
<code>
$ uname -a  
Linux hardwork 4.20.13-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 27 19:10:28 UTC 2019 x86_64 GNU/Linux  
$ pacman -Qi lxqt-...  
Name            : lxqt-...   
Version         : 0.14.0-[1-2]  
$ pacman -Qi python  
Name            : python  
Version         : 3.7.2-3  
$ pacman -Qi python-pyserial  
Name            : python-pyserial  
Version         : 3.4-2  
$ pacman -Qi python-wxpython  
Name            : python-wxpython  
Version         : 4.0.4-5  
</code>  

BTW:   
I'm using your tinybldlin fork in my Open Hardware + Free Software project for educative (and productive) purposes: a "quasi" PLC PIC16f887 based (and perhaps, optionally ATmega1284P based) that be publicly available on april 2019.  
Of course, tinybldlin software attribution for you will be granted and recognized, based on GPL license.    If you are interested, please send me a PM to danielmirkin at gmail dot com , I will reply to you including details on my project.  

Best regards,  
Daniel

**Comment by lcgamboa** [comment]
Hi Daniel,

I fixed the port detection problem and deleted the timer warnings in this commit:  271f8ab

The StatusIcon will be removed in gtk4 and gtk3 will have no substitute. I think it's best to leave it as it is until the version changes.

I'm pretty busy lately, when your project is released let me know, it seems to be very interesting.

Best regards,
Luis Claudio

**Comment by DanielPrjct** [comment]
Dear Luis Claudio Gamboa:

Congratulations! your d7cf21b commit has solved the issue about tinybldlin
not finding USB virtual serial ports.
All other features are working well.

 I'm very happy with your tinybldlin port to python3.
Thanks you!

About my OH + FS project, when it is released I will inform to you.

Best regards,


*Daniel Mirkindanielmirkin@gmail.com <danielmirkin@gmail.com>*
